// Every executable operation in the upstream toolkit is represented here.
// Shared modules (linebreak.py) are reached through their calling tools.
const A = (name, kind = 'text', help = '', optional = false) => ({name, kind, help, positional: true, required: !optional});
const V = (name, kind = 'text', help = '', required = false, repeat = false) => ({name, kind, help, required, repeat});
const B = (name, help = '') => ({name, kind: 'bool', help});
const T = (id, group, title, description, script, prefix, args, note = '') => ({id, group, title, description, script, prefix, args, note});

const tools = [
  T('build', 'Build', 'Build mod', 'Extract stock assets, render configured fonts, patch text, and repack SYSTEM.cpk.', 'build.py', [], [B('--fonts-only'),V('--sheet','file','Translation workbook for interface rows'),B('--clean','Clear the extraction cache'),B('--install','Copy the result to the Ryujinx mods folder (Windows)')], 'Requires game CPKs and font files in the project. Automatic Ryujinx install is Windows only.'),
  T('ffugen', 'Fonts', 'Generate FFU font', 'Render OTF/TTF glyphs into a template FFU, retaining unsupported glyphs.', 'tools/ffugen.py', [], [V('--template','file','Stock .ffu template',true),V('--out','save','Output .ffu',true),V('--font','file','Font chain in priority order; use path#face for TTC',true,true),V('--px','number','Explicit pixel size; blank auto fits'),V('--match-char','text','Character used for size matching'),V('--pad','number','Extra vertical padding'),V('--cell','number','Force cell height'),V('--space-ratio','number','Word space relative to n advance'),V('--glow','number','Blur before 4bpp quantization'),V('--mark-lift','number','Raise stacked Vietnamese tone marks'),V('--stroke','number','Dark outline radius; needs a dark palette entry'),V('--tracking','number','Add columns to advance'),B('--no-normalize-punctuation','Keep template bitmaps for Japanese punctuation'),B('--no-vn','Do not add Vietnamese characters')], 'A wrong cell height or invalid source font can crash the game; test the output in game.'),
  T('ffu-inspect','Fonts','Inspect FFU','Show glyph counts, heights, and metrics for chosen characters.','tools/ffu.py',[],[A('file','file','FFU file'),A('characters','text','Characters to inspect',true)]),

  T('cpk-list','Archives','List CPK','List all files and stored/extracted sizes.','tools/cpk.py',['list'],[A('archive','file')]),
  T('cpk-unpack','Archives','Unpack CPK','Extract files whose path contains the filter text.','tools/cpk.py',['unpack'],[A('archive','file'),A('filter','text','Case-insensitive path filter; blank extracts all',true),A('output folder','dir')]),
  T('cpk-repack','Archives','Repack CPK','Replace matching basenames from a folder, preserving other archived files.','tools/cpk.py',['repack'],[A('archive','file'),A('output CPK','save'),A('replacement folder','dir')]),
  T('gbnl','Archives','Inspect GBNL','Display schema and verify a bit-identical round trip for GBIN/GSTR.','tools/gbnl.py',[],[A('file','file')]),
  T('stcm2l','Archives','Inspect STCM2L','Parse and verify a DAT file or a directory of DAT files.','tools/stcm2l.py',[],[A('target','file'),B('--all','Treat target as a directory')]),
  T('tid-list','Archives','List TID textures','Show texture headers and size checks.','tools/tid.py',['list'],[A('source','file','CPK, directory, or TID'),A('filter','text','Optional path filter',true)]),
  T('tid-unpack','Archives','Decode TID textures','Decode TID textures from CPK, folder, or file into PNGs.','tools/tid.py',['unpack'],[A('source','file'),A('filter','text','Path filter; blank extracts all',true),A('output folder','dir'),B('--verbose')]),

  T('mksheet','Sheets','Create translation sheet','Extract readable STORY and SYSTEM text into an XLSX workbook.','tools/mksheet.py',[],[V('--out','save','Output XLSX',true),V('--story','file','English STORY CPK or DAT folder'),V('--system','file','English SYSTEM CPK or folder'),V('--jp-story','file','Japanese STORY CPK or folder'),V('--jp-system','file','Japanese SYSTEM CPK or folder'),B('--no-story'),B('--no-system'),B('--no-jp'),V('--font','file','FFU used for width checks'),V('--ceiling','number','Width limit'),V('--merge','file','Existing translation workbook'),B('--relink','Rebuild EN IDs while merging'),V('--sheet','text','Limit worksheet; repeat for more',false,true)], 'Keep source in column B and translation in column C. The game assets are supplied separately.'),
  T('checksheet','Sheets','Check translation sheet','Compare workbook IDs and source text against DAT files.','tools/checksheet.py',[],[A('workbook','file'),A('DAT folder','dir'),V('--sheet','text','Worksheet name',false,true)]),
  T('glossary','Sheets','Create glossary sheet','Extract interface glossary with optional Japanese pairing.','tools/glossary.py',[],[V('--system','file','SYSTEM CPK or folder'),V('--jp-system','file','Japanese SYSTEM CPK or folder'),B('--no-jp'),V('--out','save','Output XLSX')]),
  T('trbatch-prefill','Sheets','Prefill translation batch','Fill names and optionally matching dialogue from a reference workbook.','tools/trbatch.py',['prefill'],[A('sheet','file'),V('--ref','file','Reference workbook',true),V('--names','file','Name mapping'),B('--lines','Also fill verbatim matching dialogue')]),
  T('trbatch-export','Sheets','Export translation batch','Split untranslated rows into translator batches.','tools/trbatch.py',['export'],[A('sheet','file'),A('output','save'),V('--rows','number','Rows per batch')]),
  T('trbatch-import','Sheets','Import translation batch','Merge completed batch into the source workbook.','tools/trbatch.py',['import'],[A('sheet','file'),A('completed batch','file'),B('--dry-run'),B('--overwrite')]),
  T('trbatch-status','Sheets','Translation status','Count translated and untranslated rows.','tools/trbatch.py',['status'],[A('sheet','file')]),
  T('filltitles-prefixes','Sheets','Export title prefixes','Build a worksheet of chapter prefixes to translate.','tools/filltitles.py',['prefixes'],[A('incoming','file'),A('merged','file'),V('--out','save','Output XLSX')]),
  T('filltitles-fill','Sheets','Fill chapter titles','Compose title translations in the merged workbook.','tools/filltitles.py',['fill'],[A('incoming','file'),A('merged','file'),V('--prefixes','file','Translated prefixes workbook'),B('--dry-run')]),
  T('relinkjp','Sheets','Relink JP sheet','Rebuild EN ID mapping from Japanese and English script structure.','tools/relinkjp.py',[],[A('workbook','file'),V('--story','file','English STORY CPK or folder'),V('--jp-story','file','Japanese STORY CPK or folder'),V('--report','save','Unplaced rows CSV'),V('--map','save','Full mapping CSV')]),
  T('chuadich','Sheets','Find untranslated lines','Write English lines left by the translation with surrounding dialogue.','tools/chuadich.py',[],[A('incoming','file'),A('merged','file'),A('output XLSX','save')], 'Uses STORY.cpk and Japanese STORY.cpk at their documented workspace paths.'),
  T('exportvar','Sheets','Export variable text','Export the variable dialogue view to a workbook.','tools/exportvar.py',[],[A('merged workbook','file'),A('output XLSX','save'),V('--story','file','STORY CPK or folder'),V('--sheet','text','Worksheet name',false,true)]),
  T('reflow','Sheets','Reflow dialogue','Reflow translated dialogue boxes to fit the selected font width.','tools/reflow.py',[],[A('source XLSX','file'),A('output XLSX','save'),V('--story','file','STORY CPK or folder'),V('--font','file','FFU font'),V('--ceiling','number','Width limit'),V('--report','save','Overflow report CSV')]),

  T('applyvi','Apply', 'Apply translations by ID','Preferred path for workbooks generated by mksheet.','tools/applyvi.py',[],[A('workbook','file'),A('scripts','file','STORY CPK or DAT folder'),A('output folder','dir'),B('--dry-run'),V('--sheet','text','Worksheet name',false,true),B('--fit-only'),V('--font','file','FFU for width validation'),V('--ceiling','number','Width limit'),B('--fit-width'),V('--max-width','number','Maximum rendered width'),V('--max-bytes','number','Optional byte limit'),V('--report','save','Overflow CSV')]),
  T('applystory','Apply','Apply by matching text','Patch scripts from a workbook without EN IDs.','tools/applystory.py',[],[A('workbook','file'),A('DAT folder','dir'),A('output folder','dir'),V('--report','save','Unmatched rows CSV'),B('--dry-run'),B('--fuzzy'),V('--cutoff','number','Fuzzy cutoff'),V('--margin','number','Fuzzy match margin'),V('--sheet','text','Worksheet name',false,true)]),
  T('portjp2us','Apply','Port JP translation','Align and apply a JP anchored translation to another build.','tools/portjp2us.py',[],[A('workbook','file'),A('JP DAT folder','dir'),A('target DAT folder','dir'),A('output folder','dir'),B('--dry-run'),V('--sheet','text','Worksheet name',false,true),B('--fit-only'),V('--max-bytes','number','Optional byte limit')]),
  T('applyui','Apply','Apply UI translations','Rebuild translated GBIN/GSTR files, optionally repacking SYSTEM.cpk.','tools/applyui.py',[],[A('workbook','file'),A('output folder','dir'),V('--src','file','SYSTEM CPK or extracted folder'),V('--sheet','text','Worksheet name',false,true),V('--cpk','save','Also write repacked SYSTEM CPK'),B('--dry-run')]),
  T('translate-glossary','Apply','Patch sample glossary','Apply the repository’s built-in glossary examples to three GBIN/GSTR files.','tools/translate_glossary.py',[],[A('source folder','dir'),A('output folder','dir')], 'Uses hard-coded demonstration translations from upstream.'),

  T('exefs-extract','Executable','Extract ExeFS','Extract ExeFS from NSP or XCI; requires prod.keys in the expected location.','tools/exefs.py',['extract'],[A('NSP or XCI','file'),A('output folder','dir')]),
  T('exefs-segments','Executable','Decompress NSO','Write the NSO text, rodata, and data segments.','tools/exefs.py',['segments'],[A('NSO','file'),A('output folder','dir')]),
  T('exefs-strings','Executable','Find executable strings','List UTF-8 strings in an extracted segment.','tools/exefs.py',['strings'],[A('segment','file'),V('--min','number','Minimum string length'),V('--grep','text','Regex filter')]),
  T('exefs-sheet','Executable','Create executable sheet','Write matching executable strings to XLSX.','tools/exefs.py',['sheet'],[A('segment','file'),V('--out','save','Output XLSX'),V('--sheet-name','text','Worksheet name'),V('--min','number','Minimum string length'),V('--grep','text','Regex filter')]),
  T('applyexe','Executable','Apply executable sheet','Patch text in an NSO; optionally install the mod.','tools/applyexe.py',[],[A('workbook','file'),A('stock NSO','file'),A('output NSO','save'),V('--sheet','text','Worksheet name',false,true),B('--dry-run'),B('--install','Install into the emulator mods folder'),V('--title-id','text','Switch title ID'),V('--mod-name','text','Mod folder name')]),
  T('textwidth','Diagnostics','Measure text width','Compare stock dialogue line widths against the FFU font.','tools/textwidth.py',[],[A('SYSTEM CPK','file'),A('STORY CPK','file')])
];

module.exports = {tools};
